name: pylint-check

on:
  push:
    branches:
    - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone the branch
        run: git clone git@github.com:Defirence/twitchping.git
      - name: Run pylint checks.
        run: |
          echo "Running pylint against latest push..."
          pylint ./main.py